# Change these first
owner: AmericanBinary # Your GitHub organization or username, where this repository lives
repo: status.ambit.inc # The name of this repository

sites:
  - name: American Binary Website
    url: https://www.ambit.inc
  - name: Ambit Client Cloud
    url: https://ip.fortress.ambit.inc
  - name: Ambit Core Cloud
    url: https://ip.fortress.ambit.inc
  - name: Ambit Drive Cloud
    url: https://ip.fortress.ambit.inc
  - name: Ambit Customer Portal
    url: https://ambit.inc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ambit.inc
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/AmericanBinary/status.ambit.inc/master/static/img/logo.png
  name: American Binary
  introTitle: American Binary Uptime Dashboard"
  introMessage: This is the public uptime dashboard. If you are experiencing degraded service or outtage please contact us at support@ambit.inc.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
