# Change these first
owner: AmericanBinary # Your GitHub organization or username, where this repository lives
repo: status.ambit.inc # The name of this repository

sites:
  - name: American Binary Website
    url: https://www.ambit.inc
  - name: Ambit Authentication 
    url: https://auth.infra.cloud.ambit.inc
  - name: Ambit Client Admin Panel
    url: https://admin.infra.cloud.ambit.inc
  - name: Ambit Client GeoIP
    url: https://geoip.infra.cloud.ambit.inc
  - name: Ambit Customer Portal
    url: https://ambit.inc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ambit.inc
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/AmericanBinary/status.ambit.inc/1ca74e9768da61474ed0b33b739757743f576bda/assets/img/logo.png
  name: American Binary
  introTitle: American Binary Uptime Dashboard
  introMessage: This is the public uptime dashboard. If you are experiencing degraded service or outtage, please contact us at [support@ambit.inc](mailto:support@ambit.inc?subject=outtage) or call us at [+1 (408) 827-8822](tel:+14088278822).
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
